
DROP TABLE IF EXISTS price_history CASCADE;

-- CREATE PRICE_HISTORY TABLE
CREATE TABLE PRICE_HISTORY (
    SYMBOL VARCHAR(20) NOT NULL,
    TS BIGINT NOT NULL,
    PRICE NUMERIC(20, 8) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SYMBOL, TS),
    CONSTRAINT PRICE_POSITIVE CHECK (PRICE > 0),
    CONSTRAINT TS_POSITIVE CHECK (TS > 0)
);

-- COMMENTS FOR DOCUMENTATION
COMMENT ON TABLE PRICE_HISTORY IS 'STORES CRYPTOCURRENCY PRICE UPDATES FROM EXCHANGES';
COMMENT ON COLUMN PRICE_HISTORY.SYMBOL IS 'CRYPTOCURRENCY SYMBOL (E.G., BTCUSDT)';
COMMENT ON COLUMN PRICE_HISTORY.PRICE IS 'PRICE VALUE WITH 8 DECIMAL PRECISION';
COMMENT ON COLUMN PRICE_HISTORY.TS IS 'UNIX TIMESTAMP IN MILLISECONDS';
COMMENT ON COLUMN PRICE_HISTORY.CREATED_AT IS 'RECORD INSERTION TIMESTAMP';
